AWSTemplateFormatVersion: 2010-09-09
Description: "This is for simple EC2 Instance creation" # Optional Fi
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0827b6c5b977c020e"
      InstanceType: "t2.micro"
      KeyName: "fatimakey"
      SubnetId: "subnet-017e899758e3fedda"
      SecurityGroupIds:
        - !Ref MyInstanceSecurityGroup
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "ssh-and-http-https-sg"
      GroupDescription: "port 80 and 20"
      VpcId: "vpc-0927afbd8e509cb5c"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

        

